version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}  # Use the DB_PASS from .env
      MYSQL_DATABASE: ${DB_NAME}       # Use the DB_NAME from .env
      MYSQL_USER: ${DB_USER}           # Use the DB_USER from .env
      MYSQL_PASSWORD: ${DB_PASS}       # Use the DB_PASS from .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Persist MySQL data in a volume
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env  # Reference your backend's .env file here
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env  # Reference your frontend's .env file here
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

volumes:
  mysql-data:
